# HomeManager configuration file

# Use PostgreSQL database
postgres:
  # Set to true to use PostgreSQL, or else use SQLite
  enabled: false
  # Other PostgreSQL settings
  host: "localhost"
  port: 5432
  database: "home_manager"
  username: "postgres"
  # CHANGE THIS
  password: ""

# Number of homes to display per page in the /home list command
page-size: 5
